/franka_id_controller:
  ros__parameters:
    controller_name: "franka_torque_controller"
    kp:  [32.0, 24.0, 16.0, 24.0, 24.0, 16.0, 16.0]
    kd: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]
    amplitude: 10.0
