/inverseDynamicsController:
  ros__parameters:
    iiwa14:
      package_name: "example_robots"
      relative_path: "iiwa_description/urdf"
      description: "iiwa14.urdf"
      controller_name: "iiwa14_effort_controller"
      kp: [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
      kd: [8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]

/inverseDynamicsControllerVer2:
  ros__parameters:
    iiwa14:
      package_name: "example_robots"
      relative_path: "iiwa_description/urdf"
      description: "iiwa14.urdf"
      controller_name: "iiwa14_torque_controller"
      kp: [256.0, 256.0, 256.0, 256.0, 256.0, 256.0, 256.0]
      kd: [32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0]