controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    iiwa14_position_controller:
      type: position_controllers/JointGroupPositionController

    iiwa14_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    iiwa14_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    iiwa14_torque_controller:
      type: torque_controller/TorqueController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

iiwa14_torque_controller:
  ros__parameters:
    joints:
      - iiwa_joint_1 
      - iiwa_joint_2 
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
    K: [16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]
    urdf_relative_path: [example_robots, iiwa_description/urdf/iiwa14.urdf]                                                                                    

iiwa14_position_controller:
  ros__parameters:
    joints:
      - iiwa_joint_1 
      - iiwa_joint_2 
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

iiwa14_velocity_controller:
  ros__parameters:
    joints:
      - iiwa_joint_1 
      - iiwa_joint_2 
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

iiwa14_effort_controller:
  ros__parameters:
    joints:
      - iiwa_joint_1 
      - iiwa_joint_2 
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7